### ISSUE TITLE
Load-balancing destination address

### ISSUE THREAD

**Issue by aramperes** [aramperes/onetun#10]
Add support for passing multiple destination addresses for one source address. Should round-robbin the destination address to use for each incoming connection on the source address.

As suggested by @DanielBodnar

**Comment by cipriancraciun** [comment]
I'm curios what is the use-case for this feature?

(Shouldn't the load-balancing be handled at the other end?  I.e. somewhere between the Wireguard router and the actual remote server?  One could easily achieve this in a number of ways.)

**Comment by aramperes** [comment]
If you have web servers on the peers:

- 192.168.4.2:8080
- 192.168.4.3:8080

The objective is to set up a load balancer (LB) on a third system to round-robbin requests from the 2, and expose that to the internet. If you use something like [HAProxy](https://www.haproxy.com/documentation/hapee/latest/load-balancing/protocols/tcp/) or [Nginx Plus](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/), you'd need to have WireGuard installed on the LB so that the LB software is able to connect to those peers by IP.

However you can also run 1 `onetun` instance that round-robbins between the 2, and opens a single port on `0.0.0.0`. Which means:

```
                             192.168.4.2:8080
                          /
0.0.0.0:8080 -> [onetun] 
                          \
                             192.168.4.3:8080
```

Of course, you could also run multiple forwards of onetun (#2) and let an LB software do the round-robbin, but that adds an extra step in the chain:

```
                                0.0.0.0:8081 -> [      ] -> 192.168.4.2:8080
                              /                 |      |
0.0.0.0:8080 -> [LB software]                   |onetun|
                              \                 |      |
                                0.0.0.0:8082 -> [      ] -> 192.168.4.3:8080
```

**Comment by aramperes** [comment]
For what it's worth, I don't envision `onetun` being purely "utilitarian" like you said. It definitely has its uses for quickly accessing a port from a dev machine, but my own primary use-case is to set up long-running proxies for public services that are hosted from peers inside my WG network. I will keep pushing for stability and performance as much as possible.

You make a good point that letting the LB software handle the round-robin and health checks would help `onetun` be "leaner". This will only be possible once #2 is implemented though, since separate instances of onetun would need to have separate IPs/keys configured (which is a bit of a chore).
