### ISSUE TITLE
Add WireGuard endpoint setup guide

### ISSUE THREAD

**Issue by shpark** [aramperes/onetun#23]
I had to setup iptables (e.g., `sudo iptables -t nat -A POSTROUTING -s 192.168.133.0/24 -j MASQUERADE`) on the Wireguard endpoint to make port forwarding work. Is this the right thing to do? If so, it would be helpful to add server setup guide to the documentation.

**Comment by cipriancraciun** [comment]
> Is this the right thing to do?

Yes, if the host you are trying to reach (i.e. you've forwarded a port for) is on another network that is not routed by your Wireguard host, then NAT is required.  (I would say this is almost always the case.)


> If so, it would be helpful to add server setup guide to the documentation.

However, given that this is such a common scenario, and most Wireguard tutorials mention this, perhaps `onetun` is not the proper place to include this.  (This works only on Linux with `iptables`, but with newer Linux using `nftables` it's different, so is on any of the BSD's, etc.)

**Comment by shpark** [comment]
@cipriancraciun Thank you for confirming it. After reading your reply, I realized that NAT configurations required to make onetun up and running may vary across platforms and the network setup. I agree that onetun is not the right place for explaining it. Closing the issue.
