### ISSUE TITLE
Socks5 Proxy Server 

### ISSUE THREAD

**Issue by tehcneko** [aramperes/onetun#43]
Add an option to create a Socks5 proxy server that forwards all requests through the WireGuard tunnel.
Related: #38

**Comment by aramperes** [comment]
Hi @tehcneko, I've decided against embedding a SOCKS5 server directly in onetun, as the would be too many features to maintain. I [added a section](https://github.com/aramperes/onetun#httpsocks-proxy) in the README with an example on how to chain onetun with a proper SOCKS5 server such as `dante`.
