### ISSUE TITLE
Handle WireGuardError::ConnectionExpired

### ISSUE THREAD

**Issue by TitanNano** [aramperes/onetun#44]
In `wg.rs` when an `WireGuardError::ConnectionExpired` is encountered, the error is just being logged. 
https://github.com/aramperes/onetun/blob/85195d8aba2cad41b648d693044b364ab906bcf0/src/wg.rs#L123

It would be much better if this error was handled and the connection re-established.

**Comment by aramperes** [comment]
Looks like boringtun closes the UDP socket when this happens. I suppose we'd have to reopen a new one and reinitialize Tunn.

PR is welcome, otherwise I'll address this when I have time
