### ISSUE TITLE
Update to boringtun v0.6.x

### ISSUE THREAD

**Issue by aramperes** [aramperes/onetun#47]
The upgrade from `v0.4` to `v0.5` has some breaking changes, mainly with the crypto implementation having moved to a separate crate (https://github.com/cloudflare/boringtun/pull/265).

Full diff: https://github.com/cloudflare/boringtun/compare/v0.4.0...boringtun-0.5.1

**Comment by lu-zero** [comment]
[0.6.0](https://crates.io/crates/boringtun/0.6.0) got released I hadn't look yet if it is nicer to jump on it than moving to 0.5.3
