### ISSUE TITLE
arm64 build?

### ISSUE THREAD

**Issue by lendenis** [aramperes/onetun#52]
Hello,

Could you also provide arm64 build?

Thanks

**Comment by aramperes** [comment]
Hey @lendenis, are you looking for a Linux or macOS arm64 build?

**Comment by lendenis** [comment]
Hello @aramperes I am looking for Linux Arm64 build.

**Comment by sydragos** [comment]
In the meantime, you should be able to do this:
`docker build -f Dockerfile -t aramperes/onetun:arm64 .`
Then launch it with aramperes/onetun:arm64 instead of aramperes/onetun or aramperes/onetun:latest

**Comment by amalashin** [comment]
And what about macOS build? 😀

**Comment by aramperes** [comment]
> And what about macOS build? 😀

@amalashin Apple Silicon download is now available in the latest release: https://github.com/aramperes/onetun/releases/tag/v0.3.9

**Comment by aramperes** [comment]
Latest release now includes `linux-aarch64` (ARM64) as well: https://github.com/aramperes/onetun/releases/tag/v0.3.10
