### ISSUE TITLE
Library usability improvements

### ISSUE THREAD

**Issue by ghost** [aramperes/onetun#54]
`X25519SecretKey` and `X25519PublicKey` `from_str` is not compatible with `?` because it doesn't implement the trait `FromResidual`, using `thiserror` or `anyhow` should solve it.

`Config` `preshared_key` requires a `[u8; 32]` which can only easily be done at compile time not run time, switching to a `Vec<u8>` should solve it.

`Config` `endpoint_addr` requires an ip address but wireguard configs often provide domain names for dynamic dns purposes, adding a ping step should solve it.

**Comment by aramperes** [comment]
@SheaFoxx Your example `Config` is not providing any port-forwards:

```
            port_forwards: Default::default(),
```

You would need to specify at least one for `onetun` to do something. This is the equivalent configuration passed in the command-line like `onetun 127.0.0.1:8080:192.168.4.2:8080`.
